"use client";

import { ContainerScroll } from "@/components/container-scroll";
import { LimelightNav } from "@/components/limelight-nav";
import { motion, useScroll, useTransform } from "framer-motion";
import { useEffect, useState } from "react";

const photo = (id: string, width = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=88`;
const reveal = { initial: { opacity: 0, y: 32, filter: "blur(9px)" }, whileInView: { opacity: 1, y: 0, filter: "blur(0px)" } };
const destinationData = [
  { name: "Rajasthan", line: "Desert silence. Palace light. A story written in colour.", image: "photo-1477587458883-47145ed94245", className: "md:col-span-7" },
  { name: "Bali", line: "Places where every day moves at its own beautiful pace.", image: "photo-1537996194471-e657df975ab4", className: "md:col-span-5" },
  { name: "Kerala", line: "The comfort of slow water, soft mornings and a thousand greens.", image: "photo-1602216056096-3b40cc0c9944", className: "md:col-span-5" },
  { name: "Vietnam", line: "A little wild, deeply human and impossible to forget.", image: "photo-1528127269322-539801943592", className: "md:col-span-7" },
];
const styles = [["✦", "Family", "Unhurried days made for being together."], ["♡", "Honeymoon", "A beginning only the two of you can write."], ["☼", "Friends", "The kind of escape that becomes a forever story."], ["⌁", "Adventure", "For the part of you that still says yes first."], ["◌", "Luxury", "Beautifully considered, quietly extraordinary."], ["⌘", "Corporate", "Thoughtful travel for teams that go far."]];
const benefits = ["Customized itineraries", "Flexible budgets", "Comfort-first planning", "Local expertise", "Personal recommendations", "End-to-end support"];

function Logo() {
  return (
    <a href="#home" aria-label="Gowaycations home" className="flex items-center">
      <img
        src="/media/gowaycations-logo.jpeg"
        alt="Gowaycations"
        className="h-16 w-auto object-contain md:h-20"
      />
    </a>
  );
}
function Button({ children, outline = false, onClick }: { children: React.ReactNode; outline?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={`group rounded-full px-6 py-4 text-[10px] font-extrabold uppercase tracking-[.16em] transition duration-300 ${outline ? "border border-white/45 text-white hover:border-white hover:bg-white hover:text-forest" : "bg-orange text-ink hover:-translate-y-1 hover:shadow-[0_14px_32px_rgba(255,148,28,.32)]"}`}>{children} <span className="ml-2 inline-block transition group-hover:translate-x-1">↗</span></button>; }
function Reveal({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) { return <motion.div {...reveal} className={className} viewport={{ once: true, amount: .18 }} transition={{ duration: .8, delay, ease: [0.16, 1, .3, 1] }}>{children}</motion.div>; }

export default function Home() {
 const { scrollY } = useScroll();
const heroTextY = useTransform(scrollY, [0, 700], [0, 135]);
  const scrollTo = (target: string) => () => document.getElementById(target)?.scrollIntoView({ behavior: "smooth" });
  const nav = [["Home", "home", "⌂"], ["Destinations", "destinations", "◈"], ["Travel Styles", "styles", "✦"], ["About", "about", "○"], ["Contact", "contact", "↗"]].map(([label, id, icon]) => ({ id, label, onClick: scrollTo(id), icon: <span>{icon}</span> }));
  return <main className="overflow-hidden">
<header className="fixed inset-x-0 top-0 z-50 mx-auto flex max-w-[1500px] items-center justify-between px-4 pt-4 md:px-10 md:pt-5">
<div className="flex w-full items-center justify-between rounded-full border border-white/20 bg-black/20 px-4 py-2.5 backdrop-blur-2xl shadow-[0_10px_35px_rgba(0,0,0,.18)] md:px-6">        <LimelightNav items={nav} className="hidden lg:inline-flex" />
        <button onClick={scrollTo("contact")} className="rounded-full bg-orange px-5 py-3 text-[10px] font-extrabold uppercase tracking-[.15em] text-ink shadow-[0_8px_24px_rgba(255,148,28,.25)] transition hover:scale-105">◉&nbsp; WhatsApp us</button>
      </div>
    </header>

    <section id="home" className="relative min-h-[1060px] bg-[#111] text-white md:min-h-[1150px]">
      <video autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover"><source src="/media/goway-hero.mp4" type="video/mp4" /></video>
      <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(10,12,8,.75)_0%,rgba(10,12,8,.16)_38%,#111_91%)]" />
      <div className="absolute left-[10%] top-[28%] h-72 w-72 rounded-full bg-orange/15 blur-[120px]" />
      <motion.div style={{ y: heroTextY }} className="relative z-10 pt-36 md:pt-40">
        <ContainerScroll titleComponent={<div className="px-4"><motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 }} className="eyebrow mb-5 text-orange">Gowaycations</motion.p><motion.h1 initial={{ opacity: 0, y: 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1, delay: .28, ease: [0.16, 1, .3, 1] }} className="mx-auto max-w-6xl text-[clamp(3.5rem,8vw,8.4rem)] font-medium leading-[.86] tracking-[-.085em]">Travel the way<br /><em className="font-light">you choose.</em></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .75 }} className="mx-auto mt-7 max-w-2xl text-sm leading-7 text-white/80 md:text-base">Every journey is different. That&apos;s why every itinerary we create is tailored to your comfort, travel style and budget.</motion.p><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .95 }} className="mt-8 flex flex-wrap justify-center gap-3"><Button onClick={scrollTo("contact")}>Plan my trip</Button><Button outline onClick={scrollTo("destinations")}>Explore destinations</Button></motion.div></div>}>
          <div className="relative h-full overflow-hidden bg-black"><video autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover"><source src="/media/goway-hero.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/5 to-black/15" /><div className="relative flex h-full flex-col justify-between p-5 text-white md:p-8"><div className="flex items-center justify-between text-[10px] font-semibold uppercase tracking-[.2em]"><span>Your journey begins here<span className="text-orange">•</span></span><span>01 / 01</span></div><div className="flex items-end justify-between"><div><p className="eyebrow text-orange">Explore the world</p><div className="mt-3 h-px w-40 bg-white/60" /></div><div className="hidden text-center md:block"><span className="mx-auto block h-10 w-6 rounded-full border border-white/70 p-1"><i className="block h-2 w-1 rounded-full bg-white" /></span><p className="mt-3 text-[9px] font-semibold uppercase tracking-[.2em] text-white/70">Scroll to discover</p></div><span className="text-xl">⌁</span></div></div></div>
        </ContainerScroll>
      </motion.div>
    </section>

    <section className="relative -mt-12 bg-[#12170f] py-24 text-white md:-mt-20"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(#516131_1px,transparent_1px)] [background-size:18px_18px]" /><div className="section-shell relative grid gap-10 lg:grid-cols-[1.05fr_1.45fr] lg:items-end"><Reveal><p className="eyebrow text-orange">Our specialisation</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-[.98] tracking-[-.065em] md:text-6xl">We customise every trip around <em className="font-light text-orange">your comfort and budget.</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/65">You deserve more than a pre-set itinerary. Tell us how you want to travel; we create the experience around you.</p></Reveal><div className="grid grid-cols-2 gap-x-4 gap-y-8 md:grid-cols-3">{benefits.map((benefit, i) => <Reveal key={benefit} delay={i * .06}><div className="border-l border-white/15 pl-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-lg text-orange">{["◌", "◐", "♡", "✦", "⌁", "◉"][i]}</span><p className="mt-3 text-sm font-medium leading-snug">{benefit}</p></div></Reveal>)}</div></div></section>

    <section id="destinations" className="section-shell py-28 md:py-36"><Reveal><p className="eyebrow text-orange">Made for the moment</p><h2 className="mt-5 max-w-5xl text-5xl font-medium leading-[.92] tracking-[-.07em] md:text-8xl">The world does not come in a <em className="font-light">template.</em></h2><p className="mt-7 max-w-xl text-sm leading-7 text-black/55">From a weekend close to home to a journey across the ocean, every route begins with how you want to feel.</p></Reveal><div className="mt-16 grid gap-5 md:grid-cols-12">{destinationData.map((destination, index) => <Reveal key={destination.name} delay={index * .1} className={destination.className}><article className="group image-shine relative h-[490px] overflow-hidden rounded-[32px] bg-forest md:h-[590px]"><img src={photo(destination.image)} alt={destination.name} loading="lazy" className="h-full w-full object-cover transition duration-[1.2s] group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/5 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white md:p-9"><p className="text-[clamp(2.6rem,4vw,4.5rem)] font-medium tracking-[-.07em]">{destination.name}</p><p className="mt-2 max-w-sm text-sm leading-6 text-white/75">{destination.line}</p><div className="mt-5 flex flex-wrap gap-2 text-[9px] font-bold uppercase tracking-[.12em]"><span className="rounded-full border border-white/35 px-3 py-2">✓ Fully customizable</span><span className="rounded-full border border-white/35 px-3 py-2">✓ Your comfort first</span></div></div></article></Reveal>)}</div></section>

    <section className="bg-mist py-28 md:py-36"><div className="section-shell"><Reveal><p className="eyebrow text-orange">Your story, in motion</p><h2 className="mt-5 max-w-3xl text-5xl font-medium leading-[.94] tracking-[-.07em] md:text-7xl">Dream it. Discover it. Experience it. <em className="font-light">Remember it.</em></h2></Reveal><div className="mt-16 grid gap-5 md:grid-cols-2">{[["Dream", "The first feeling. A place you have never seen, already calling your name.", "photo-1500534623283-312aade485b7"], ["Discover", "The little turn you did not expect. The local secret you will never forget.", "photo-1548013146-72479768bada"], ["Experience", "A table under the stars. The view that makes the whole day quiet.", "photo-1500530855697-b586d89ba3ee"], ["Remember", "The people you went with. The version of you that came home.", "photo-1529156069898-49953e39b3ac"]].map(([word, copy, image], i) => <Reveal delay={i * .1} key={word}><motion.article whileHover={{ y: -8 }} className="group relative flex min-h-[380px] items-end overflow-hidden rounded-[30px] p-7 text-white md:p-9"><img src={photo(image, 1200)} alt="" loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-[1.2s] group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/10 to-transparent" /><div className="relative"><p className="text-5xl font-light tracking-[-.07em]">{word}</p><p className="mt-3 max-w-sm text-sm leading-6 text-white/75">{copy}</p></div><span className="absolute right-7 top-7 text-orange">0{i + 1}</span></motion.article></Reveal>)}</div></div></section>

    <section id="styles" className="bg-[#151a11] py-28 text-white md:py-36"><div className="section-shell"><Reveal><p className="eyebrow text-orange">Your kind of escape</p><h2 className="mt-5 text-5xl font-medium tracking-[-.07em] md:text-7xl">Choose the feeling.</h2></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{styles.map(([icon, title, copy], i) => <Reveal delay={i * .06} key={title}><motion.article whileHover={{ y: -8, rotate: i % 2 ? 1 : -1 }} className="group min-h-[240px] rounded-[28px] border border-white/10 bg-white/[.055] p-7 backdrop-blur-sm transition hover:bg-white/[.1]"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-orange/15 text-2xl text-orange transition duration-500 group-hover:rotate-12 group-hover:bg-orange group-hover:text-ink">{icon}</span><h3 className="mt-12 text-2xl font-medium tracking-[-.055em]">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{copy}</p></motion.article></Reveal>)}</div></div></section>

    <section id="about" className="section-shell grid gap-12 py-28 md:py-36 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><p className="eyebrow text-orange">The Gowaycations difference</p><h2 className="mt-5 text-5xl font-medium leading-[.94] tracking-[-.07em] md:text-7xl">We plan for the way you want to <em className="font-light">live the journey.</em></h2><p className="mt-8 max-w-lg text-sm leading-7 text-black/60">No fixed packages. No being told what your holiday should look like. Just thoughtful planning, trusted local insight and a travel expert who listens before they recommend.</p><Button onClick={scrollTo("contact")}>Let&apos;s plan your journey</Button></Reveal><Reveal delay={.15}><div className="relative min-h-[540px] overflow-hidden rounded-[36px] bg-forest"><img src={photo("photo-1464822759023-fed622ff2c3b")} alt="A tailor-made mountain journey" loading="lazy" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-forest via-forest/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 grid grid-cols-2 gap-px bg-white/10"><div className="bg-forest/80 p-6 text-white backdrop-blur"><b className="text-2xl">01</b><p className="mt-2 text-xs text-white/65">We listen to your travel wishes.</p></div><div className="bg-forest/80 p-6 text-white backdrop-blur"><b className="text-2xl">02</b><p className="mt-2 text-xs text-white/65">We shape every detail around you.</p></div></div></div></Reveal></section>

    <section className="bg-[#f4f2ec] py-28 md:py-36"><div className="section-shell"><Reveal><p className="eyebrow text-orange">From our travellers</p><h2 className="mt-5 text-5xl font-medium tracking-[-.07em] md:text-7xl">The feeling stays with you.</h2></Reveal><div className="mt-14 grid gap-5 lg:grid-cols-3"><Reveal><blockquote className="min-h-[330px] rounded-[32px] bg-white p-8 shadow-[0_20px_45px_rgba(17,17,17,.06)]"><span className="text-orange">★★★★★</span><p className="mt-8 text-2xl font-medium leading-snug tracking-[-.045em]">“They understood our pace before we did. It never felt planned; it simply felt like us.”</p><footer className="mt-10 text-xs font-bold">Ananya & Rohan <span className="font-normal text-black/45">· A honeymoon in Bali</span></footer></blockquote></Reveal><Reveal delay={.1}><blockquote className="min-h-[330px] rounded-[32px] bg-forest p-8 text-white shadow-[0_20px_45px_rgba(17,17,17,.1)]"><span className="text-orange">★★★★★</span><p className="mt-8 text-2xl font-medium leading-snug tracking-[-.045em]">“Every transfer, every stay, every small request was quietly taken care of.”</p><footer className="mt-10 text-xs font-bold">Amit Mehra <span className="font-normal text-white/55">· Family journey through Kerala</span></footer></blockquote></Reveal><Reveal delay={.2}><blockquote className="min-h-[330px] rounded-[32px] bg-orange p-8 text-ink shadow-[0_20px_45px_rgba(17,17,17,.08)]"><span className="text-forest">★★★★★</span><p className="mt-8 text-2xl font-medium leading-snug tracking-[-.045em]">“Not a package. A beautiful, effortless story we got to step inside.”</p><footer className="mt-10 text-xs font-bold">Neha Kapoor <span className="font-normal text-black/55">· Friends&apos; escape to Vietnam</span></footer></blockquote></Reveal></div></div></section>

    <section id="contact" className="relative min-h-[620px] overflow-hidden bg-[#10140d] text-white"><video autoPlay muted loop playsInline preload="none" className="absolute inset-0 h-full w-full object-cover opacity-50"><source src="/media/goway-hero.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-gradient-to-r from-[#11170f]/95 via-[#11170f]/60 to-[#11170f]/30" /><div className="section-shell relative flex min-h-[620px] items-center py-24"><Reveal><p className="eyebrow text-orange">Your story starts here</p><h2 className="mt-6 max-w-4xl text-5xl font-medium leading-[.92] tracking-[-.075em] md:text-8xl">The world is waiting.<br /><em className="font-light">Where will your story begin?</em></h2><p className="mt-7 max-w-xl text-sm leading-7 text-white/70">Tell us your idea, your comfort level and the way you want to travel. We will take it from there.</p><div className="mt-9"><Button onClick={() => undefined}>Let&apos;s plan your journey</Button></div></Reveal></div></section>

    <footer className="bg-forest px-[5vw] py-14 text-white"><div className="mx-auto grid max-w-[1400px] gap-10 md:grid-cols-[1.5fr_1fr_1fr]"><div><Logo dark /><p className="mt-5 max-w-sm text-xs leading-6 text-white/65">Personalised travel, planned with care from Bengaluru to the world.</p></div><div><p className="eyebrow text-orange">Explore</p><p className="mt-5 text-xs leading-7 text-white/65">Destinations<br />Travel styles<br />How we customise</p></div><div><p className="eyebrow text-orange">Find us</p><p className="mt-5 text-xs leading-7 text-white/65">1599, 25th B Main Road,<br />BDA Layout, HSR Layout,<br />Bengaluru · 560102<br /><br />Instagram · WhatsApp · Email</p></div></div><div className="mx-auto mt-12 max-w-[1400px] border-t border-white/15 pt-5 text-[10px] tracking-wide text-white/45">© 2026 Gowaycations. Travel the way you choose.</div></footer>
  </main>;
}
